apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "two-tier-flask-app.fullname" . }}
data:
  MYSQL_HOST: {{ .Values.configMap.MYSQL_HOST | quote }}
  MYSQL_DB: {{ .Values.configMap.MYSQL_DB | quote }}
