{{- if .Values.mysqlCluster.enabled }}
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: {{ include "two-tier-flask-app.fullname" . }}-db
spec:
  secretName: {{ include "two-tier-flask-app.fullname" . }}
  instances: {{ .Values.mysqlCluster.instances }}
  router:
    instances: {{ .Values.mysqlCluster.routerInstances }}
  datadirVolumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: {{ .Values.mysqlCluster.storage.storageClassName }}
    resources:
      requests:
        storage: {{ .Values.mysqlCluster.storage.capacity }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "two-tier-flask-app.fullname" . }}-mysql-init
data:
  init.sql: |
    {{ .Values.mysqlCluster.initSQL | nindent 4 }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "two-tier-flask-app.fullname" . }}-mysql-pv
spec:
  capacity:
    storage: {{ .Values.mysqlCluster.storage.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.mysqlCluster.storage.storageClassName }}
  hostPath:
    path: {{ .Values.mysqlCluster.storage.hostPath }}
    type: DirectoryOrCreate
{{- end }}
