apiVersion: v1
kind: Secret
metadata:
  name: {{ include "two-tier-flask-app.fullname" . }}
type: Opaque
data:
  MYSQL_DATABASE: {{ .Values.mysqlCluster.database | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysqlCluster.rootPassword | b64enc }}
  MYSQL_USER: {{ .Values.mysqlCluster.user | b64enc }}
  MYSQL_PASSWORD: {{ .Values.mysqlCluster.password | b64enc }}
  rootUser: {{ .Values.mysqlCluster.user | b64enc }}
  rootHost: {{ .Values.mysqlCluster.rootHost | b64enc }}
  rootPassword: {{ .Values.mysqlCluster.rootPassword | b64enc }}
